/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numcircularesprimos;
import common.Common;
import static java.lang.Math.log10;
import threads.*;
/**
 *
 * @author Rodrigo
 */
public class NumerosCircularesPrimos extends javax.swing.JFrame {

    /**
     * Creates new form NumerosCircularesPrimos
     */
    public NumerosCircularesPrimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtVerificarNumero = new javax.swing.JTextField();
        btnVerificaNumero = new javax.swing.JButton();
        lblVerificarNumero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtObtenerPrimosCirculares = new javax.swing.JTextField();
        btnObtenerPrimosCirculares = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Números Primos Circulares");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Verificar Si Un Número Es Primo Circular", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Número:");

        txtVerificarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerificarNumeroActionPerformed(evt);
            }
        });

        btnVerificaNumero.setText("¿Es primo circular?");
        btnVerificaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerificarNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerificarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerificaNumero)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVerificarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificaNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerificarNumero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Obtener Primos Circulares Menores Que Un Número Determinado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Número Tope:");

        txtObtenerPrimosCirculares.setText("1000000");
        txtObtenerPrimosCirculares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObtenerPrimosCircularesActionPerformed(evt);
            }
        });

        btnObtenerPrimosCirculares.setText("Obtener Primos Circulares");
        btnObtenerPrimosCirculares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerPrimosCircularesActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObtenerPrimosCirculares, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnObtenerPrimosCirculares)
                        .addGap(0, 195, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtObtenerPrimosCirculares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtenerPrimosCirculares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerificarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerificarNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerificarNumeroActionPerformed

    private void txtObtenerPrimosCircularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObtenerPrimosCircularesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObtenerPrimosCircularesActionPerformed

    private void btnVerificaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaNumeroActionPerformed
        String txtNumero = this.txtVerificarNumero.getText().trim().replace(".", "");
        if(!txtNumero.equals("")){
            try{
            int resul = Integer.valueOf(txtNumero);
            if(((int)(log10(resul)+1)) > 1){
                         if(Common.esPrimo(resul) == Common.Resultado.ESPRIMO){
            
            Common.Resultado res = Common.esPrimoCircular(Integer.parseInt(txtNumero));
            
            switch(res){
                case ESPRIMOCIRCULAR:
                    this.lblVerificarNumero.setText( "El número " + txtNumero 
                            + " es primo circular. Sus primos circulares son: " + Common.getListaCirculares());
                    break;
                case NUMEROUNACIFRA:
                     this.lblVerificarNumero.setText("Debe ingresar un número de al menos dos cifras.");
                    break;

                    
                case NUMERONOPRIMOCIRCULAR:
                     this.lblVerificarNumero.setText("El número " + txtNumero + " es primo, pero no circular, ya que al menos uno de sus circulares no es primo.");
            }
            }else{
                     this.lblVerificarNumero.setText("El número " + txtNumero + " no es un número primo.");
            }
            }else{
               this.lblVerificarNumero.setText("Debe ingresar un número de al menos 2 dígitos para poder calcular primos circulares.");
            }

            }
            catch(NumberFormatException e){
            this.lblVerificarNumero.setText("Error: Se aceptan sólo números entre 0 y  2.147.483.646");
            }
  

        }else{
        this.lblVerificarNumero.setText("Debe ingresar algún número.");
        }
    }//GEN-LAST:event_btnVerificaNumeroActionPerformed

    private void btnObtenerPrimosCircularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerPrimosCircularesActionPerformed
      String txtTope = this.txtObtenerPrimosCirculares.getText().trim().replace(".", "");
      this.jTextArea1.setText("");

      
      if(!txtTope.equals("")){
          this.lblError.setText("");
          try{
         int numTop =  Integer.parseInt(txtTope);
            if(((int)(log10(numTop)+1)) > 1){
                               NumPrimos.setTerminoGenerar(false);
          NumPrimos.resetCantidadPrimosCirculares();
                this.btnObtenerPrimosCirculares.setEnabled(false);
            this.jTextArea1.setText("Comenzando el procesamiento... \n");
            GeneradorNumerosPrimosThread threadGenNumPrim= new GeneradorNumerosPrimosThread();
            threadGenNumPrim.setTopeIteracion(numTop);
            GeneradorNumerosPrimosCircularesThread threadGenNumPrimCir = new GeneradorNumerosPrimosCircularesThread(this.jTextArea1, this.btnObtenerPrimosCirculares);

            threadGenNumPrim.start();
            threadGenNumPrimCir.start();
            }else{
            this.lblError.setText("Debe ingresar un número de al menos 2 dígitos para poder calcular primos circulares.");
            }

          }catch(NumberFormatException e){
                      this.lblError.setText("Error: Se aceptan sólo números entre 0 y  2.147.483.646");
          }

      }else{
      this.lblError.setText("Debe ingresar algún número.");
      }
    }//GEN-LAST:event_btnObtenerPrimosCircularesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosCircularesPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosCircularesPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosCircularesPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosCircularesPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosCircularesPrimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObtenerPrimosCirculares;
    private javax.swing.JButton btnVerificaNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblVerificarNumero;
    private javax.swing.JTextField txtObtenerPrimosCirculares;
    private javax.swing.JTextField txtVerificarNumero;
    // End of variables declaration//GEN-END:variables
}
